# Generated by Django 4.2.6 on 2023-10-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='user_profiles', to='users.skill'),
        ),
    ]
