# Generated by Django 4.2.6 on 2023-10-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cv',
            new_name='github_profile',
        ),
    ]
