# Generated by Django 4.2.6 on 2023-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_cv_customuser_github_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_profile',
            field=models.URLField(null=True),
        ),
    ]
