# Generated by Django 4.2.6 on 2023-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_github_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_mentored',
            field=models.BooleanField(default=False),
        ),
    ]
