# Generated by Django 4.2.6 on 2023-10-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmentors',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mentor_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmentors',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mentors', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventmentors',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mentors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmentors',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mentors_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
